name: 

on:
  push: 
    branchs: ["main"]
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Đăng nhập docker hub
        run: docker login -u tienhiendev -p ${{secrets.PASS_SECRET}}

      - name: Build image
        run: docker build -t tienhiendev/img-be_apartment_bussiness:latest .

      - name: Push Image lên docker hub 